### ISSUE TITLE
`-D` option not working ?

### ISSUE THREAD

**Issue by the-real-adammork** [ddelange/yt#2]
Just installed, and Im excited to use this project ! Exactly what I need for something. But when I use the `-D` option I get an error:

![Screen Shot 2021-04-24 at 2 17 25 AM](https://user-images.githubusercontent.com/407743/115953993-56ee1480-a4a3-11eb-862f-a33f7c2df115.png)

Not a blocker for me I can pull from the default download directory but figured you might want to know.

Thanks for this project, starred it !

**Comment by ddelange** [comment]
Interesting catch, thanks for reporting!

I must admit I dont use -D myself, and have tested this approach only for the integer flags. Maybe I'm overlooking something though, as it seems the `/tmp` arg is not consumed in this line, and instead gets passed to URLS a bit further down.

https://github.com/ddelange/yt/blob/0.2.2/yt/yt#L53

Will need to investigate further!

**Comment by the-real-adammork** [comment]
Ok cool Ill take look as well

**Comment by ddelange** [comment]
Maybe it gets consumed (destination is set as expected), but then the OPTIND shift allows it to get consumed a second time in filling URLS, or something similar.

Another possibility is removing the double quotes from here, just a hunch... https://github.com/ddelange/yt/blob/0.2.2/yt/yt#L154

**Comment by the-real-adammork** [comment]
I tried w/ and w/o quotes

**Comment by ddelange** [comment]
Released [`0.3.0`](https://github.com/ddelange/yt/releases/0.3.0), once the [tap PR](https://github.com/ddelange/homebrew-brewformulae/pull/12) auto-merges, please run `brew upgrade yt` :)

**Comment by the-real-adammork** [comment]
![Screen Shot 2021-04-24 at 4 29 11 AM](https://user-images.githubusercontent.com/407743/115957139-a0dff600-a4b5-11eb-996c-dd9e8846644b.png)

Maybe not fully fixed ?

Im semi-intermediate with bash so Im happy to take a look tomorrow, no rush not a blocker. 

Heres the project im working on:

https://github.com/the-real-adammork/yt-extension
https://github.com/the-real-adammork/yt-server

started tonight, made it so I can speed up my music digging workflow. Idea is to have the chrome extension send requests to the express server on localhost to download whatever audio is in the current tab (soundcloud/youtube).

Right now it activates when you click the extension icon, I think I'll add keyboard shortcut as well.

Im glad I came across your project seems like it improves on `youtube-dl` in all the ways Id like and the take from clipboard by default is really smart, that was actually part of my old script. 

Thanks 🦾

**Comment by ddelange** [comment]
Thanks for checking!! Fixed in [`0.3.1`](https://github.com/ddelange/yt/releases/0.3.1).

Your project sounds really cool! The extension would definitely save clicks and make the flow more natural!

If you encounter any bugs in the future, please let me know. And also feel free to tag me on your PRs or so if you need a second pair of eyes :)
