### ISSUE TITLE
Install Problem on OsX Monterey 12.6

### ISSUE THREAD

**Issue by sbonaime** [ddelange/yt#5]
brew install ddelange/brewformulae/yt                         

==> Tapping ddelange/brewformulae
Cloning into '/usr/local/Homebrew/Library/Taps/ddelange/homebrew-brewformulae'...
remote: Enumerating objects: 143, done.
remote: Counting objects: 100% (95/95), done.
remote: Compressing objects: 100% (68/68), done.
remote: Total 143 (delta 21), reused 84 (delta 13), pack-reused 48
Receiving objects: 100% (143/143), 31.70 KiB | 5.28 MiB/s, done.
Resolving deltas: 100% (29/29), done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/ddelange/homebrew-brewformulae/Formula/spek.rb
spek: undefined method `cask' for Formulary::FormulaNamespace3bbcb78e93dd3039825a3b792493d41b:Module
Did you mean?  case
Error: Cannot tap ddelange/brewformulae: invalid syntax in tap!

**Comment by ddelange** [comment]
ref https://github.com/ddelange/homebrew-brewformulae/commit/cfb1d0a4d2a2f1df284346b5df3843779ba9bf24

can you try now?

**Comment by ddelange** [comment]
hi @sbonaime 👋

did the installation succeed?

**Comment by ddelange** [comment]
please comment here or open another issue if you still experience problems!

**Comment by sbonaime** [comment]
Well... I upgrade my system to Ventura and I need to re-install Xcode but I am running out of space ! So I don't know if the fix is working...
Thanks
